config/routes.rb
Rails.application.routes.draw do
  
  resources :irisplants

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'irisplants#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/hybridizer.rb
class Hybridizer < ActiveRecord::Base
  has_many :irisplants
end

app/models/irisplant.rb
class Irisplant < ActiveRecord::Base
  belongs_to :hybridizer

  # scope :sibtype, Irisplant.all.where(iristype: :SIB)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/hybridizers_controller.rb
class HybridizersController < InheritedResources::Base
  before_action :set_hybridizer, only: [:show, :edit, :update, :destroy]

  def index
    @hybridizers = Hybridizer.all
  end

  def show
  end

  def new
    @hybridizer = Hybridizer.new
  end

  def edit
  end

  def create
    @hybridizer = Hybridizer.new(hybridizer_params)

    respond_to do |format|
      if @hybridizer.save
        format.html { redirect_to @hybridizer, notice: 'Successfully created hybridizer'}
      else
        format.html { render :new}
      end
    end
  end

  def update
    respond_to do |format|
      if @hybridizer.update(hybridizer_params)
        format.html {redirect_to @hybridizer, notice: 'Successfully updated hybridizer'}
      else
        format.html {render :edit}
      end
    end
  end

  def destroy
    @hybridizer.destroy
    respond_to do |format|
      format.html { redirect_to hybridizer_url, notice: 'hybridizer deleted'}
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hybridizer
      @hybridizer = Hybridizer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hybridizer_params
      params.require(:hybridizer).permit(:firstname, :lastname)
    end
end

app/controllers/irisplants_controller.rb
class IrisplantsController < ApplicationController
  before_action :set_irisplant, only: [:show, :edit, :update, :destroy]
  has_scope :sibtype

  # GET /irisplants
  # GET /irisplants.json
  def index
    @hybridizers = Hybridizer.order(lastname: :asc)

    if params[:iristype]
      @irisplants = Irisplant.all.where(iristype: params[:iristype])
    elsif params[:hybridizer]
      @irisplants = Irisplant.where(:hybridizer_id => params[:hybridizer])
    else
      @irisplants = Irisplant.all
    end
    # @irisplants = apply_scopes(Irisplant).all
  end

  # GET /irisplants/1
  # GET /irisplants/1.json
  def show
  end

  # GET /irisplants/new
  def new
    @irisplant = Irisplant.new
    @gardens = ["Aitken", "Mt Pleasant", "Miller", "Wild", "Mid America", "Schreiners"]
  end

  # GET /irisplants/1/edit
  def edit
  end

  # POST /irisplants
  # POST /irisplants.json
  def create
    @irisplant = Irisplant.new(irisplant_params)

    respond_to do |format|
      if @irisplant.save
        format.html { redirect_to @irisplant, notice: 'Irisplant was successfully created.' }
        format.json { render :show, status: :created, location: @irisplant }
      else
        format.html { render :new }
        format.json { render json: @irisplant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /irisplants/1
  # PATCH/PUT /irisplants/1.json
  def update
    respond_to do |format|
      if @irisplant.update(irisplant_params)
        format.html { redirect_to @irisplant, notice: 'Irisplant was successfully updated.' }
        format.json { render :show, status: :ok, location: @irisplant }
      else
        format.html { render :edit }
        format.json { render json: @irisplant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /irisplants/1
  # DELETE /irisplants/1.json
  def destroy
    @irisplant.destroy
    respond_to do |format|
      format.html { redirect_to irisplants_url, notice: 'Irisplant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_irisplant
      @irisplant = Irisplant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def irisplant_params
      params.require(:irisplant).permit(:hybridizer_id, :name, :region, :year, :image_url, :iristype, :garden)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hybridizers_helper.rb
module HybridizersHelper
end

app/helpers/irisplants_helper.rb
module IrisplantsHelper
end

app/views/hybridizers/_form.html.erb
<%= form_for(@hybridizer) do |f| %>
  <% if @hybridizer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hybridizer.errors.count, "error") %> prohibited this hybridizer from being saved:</h2>

      <ul>
      <% @hybridizer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :irisplant_id %><br>
    <%= f.number_field :irisplant_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hybridizers/edit.html.erb
<h1>Editing hybridizer</h1>

<%= render 'form' %>

<%= link_to 'Show', @hybridizer %> |
<%= link_to 'Back', hybridizers_path %>

app/views/hybridizers/index.html.erb
<h1>Listing hybridizers</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Irisplant</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hybridizers.each do |hybridizer| %>
      <tr>
        <td><%= hybridizer.firstname %></td>
        <td><%= hybridizer.lastname %></td>
        <td><%= hybridizer.irisplant_id %></td>
        <td><%= link_to 'Show', hybridizer %></td>
        <td><%= link_to 'Edit', edit_hybridizer_path(hybridizer) %></td>
        <td><%= link_to 'Destroy', hybridizer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hybridizer', new_hybridizer_path %>

app/views/hybridizers/new.html.erb
<h1>New hybridizer</h1>

<%= render 'form' %>

<%= link_to 'Back', hybridizers_path %>

app/views/hybridizers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @hybridizer.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @hybridizer.lastname %>
</p>

<p>
  <strong>Irisplant:</strong>
  <%= @hybridizer.irisplant_id %>
</p>

<%= link_to 'Edit', edit_hybridizer_path(@hybridizer) %> |
<%= link_to 'Back', hybridizers_path %>

app/views/irisplants/_form.html.erb
<%= form_for(@irisplant) do |f| %>
  <% if @irisplant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@irisplant.errors.count, "error") %> prohibited this irisplant from being saved:</h2>

      <ul>
      <% @irisplant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :hybridizer %><br>
    <%= f.text_field :hybridizer %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :region %><br>
    <%= f.number_field :region %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :iristype %><br>
    <%= f.text_field :iristype %>
  </div>
  <div class="field">
    <%= f.label :garden %><br>
    <%= f.select(:garden, @gardens.map { |value| [value, value] }) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/irisplants/edit.html.erb
<h1>Editing irisplant</h1>

<%= render 'form' %>

<%= link_to 'Show', @irisplant %> |
<%= link_to 'Back', irisplants_path %>

app/views/irisplants/index.html.erb
<h1>Listing irises</h1>


    <!-- Post Row -->
<div id="blog">

  <h3 class="text alert alert-success">Initial selection of Irises that are part of the 2014/2015 Oregon Garden Tours
  </h3>

  <div class="row post_row">
    <% if @irisplants.empty? %>
      <h4 class="well">That hybridizer does not have any Irises in the database yet.</h3>
    <% else %>
      <% @irisplants.each do |irisplant| %>
        <div class="span8 well">
          <div class="text">
            <h2><%= irisplant.name %></h2>
            <p>Region: <%= irisplant.region %>
            Year: <%= irisplant.year %>
            <!-- <p><%= irisplant.image_url %></p> -->
            Type: <%= irisplant.iristype %></p>
              
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/irisplants/new.html.erb
<h1>New irisplant</h1>

<%= render 'form' %>

<%= link_to 'Back', irisplants_path %>

app/views/irisplants/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Hybridizer:</strong>
  <%= @irisplant.hybridizer %>
</p>
<p>
  <strong>Name:</strong>
  <%= @irisplant.name %>
</p>

<p>
  <strong>Region:</strong>
  <%= @irisplant.region %>
</p>

<p>
  <strong>Year:</strong>
  <%= @irisplant.year %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @irisplant.image_url %>
</p>

<p>
  <strong>Iristype:</strong>
  <%= @irisplant.iristype %>
</p>

<%= link_to 'Edit', edit_irisplant_path(@irisplant) %> |
<%= link_to 'Back', irisplants_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Iriscodex" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <!-- <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a> -->
          <a class="brand" href="/"><h2>Iriscodex</h2></a>
          <span class="right"><%= link_to "Login", new_admin_user_session_path  %></span>
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>

          </div>
          <div class="span3">
            <div class="well sidebar-nav sidebar-pos">
<!--               <h3>Sort Irises</h3>
 -->              <ul class="nav nav-list">
                <li><%= link_to "Show All", irisplants_path  %></li>
                <li class="nav-header">Sort Irises</li>
                <li>By Iris Type</li>
                <li><%= link_to "SIB Types", irisplants_path(iristype: :SIB)  %></li>
                <li><%= link_to "PCI Types", irisplants_path(iristype: :PCI)  %></li>
                <br/>
                <li>By Hybridizer</li>
                <% @hybridizers.each do |h| %>
                  <li><%= link_to h.lastname, irisplants_path(hybridizer: h.id) %></li>
                <% end -%>
          
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->
      <footer>
        <p>&copy; diligentagility 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/irises.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Iriscodex" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Iriscodex</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="span3">
            <div class="well sidebar-nav">
              <h3>Sidebar</h3>
              <ul class="nav nav-list">
                <li class="nav-header">Sidebar</li>
                <li><%= link_to "Link1", "/path1"  %></li>
                <li><%= link_to "Link2", "/path2"  %></li>
                <li><%= link_to "Link3", "/path3"  %></li>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>